// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://isebnwniefoaywvvjorp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZWJud25pZWZvYXl3dnZqb3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTc3MTQsImV4cCI6MjA3MDc3MzcxNH0.Rk9U5Fu0feQ9BYXyH7E8cOgpLl3BK0zzFcNpTCjRmU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);